### ISSUE TITLE
알고리즘 - openCV영상 함수 정리

### ISSUE THREAD

**Issue by KwangEun** [CUDTeam3/SmarkCrosswalk_WebCam#3]
1. openCV 함수 정리 및 활용 방안 소개

**Comment by sadcookie** [comment]
1. 영상 흑백 변환
   1. 백색 증가량 감지
   2. 흑색 증가량 감지
2. 경계화
3. 객체 검출
   1. 캐스케이드
      1. 보행자 데이터 셋을 이용한 검출 

보행자 데이터 셋
MIT - http://cbcl.mit.edu/software-datasets/PedestrianData.html
INRIA - http://pascal.inrialpes.fr/data/human/
ETH - https://data.vision.ee.ethz.ch/cvl/aess/dataset/
MPG - https://www.mpi-inf.mpg.de/departments/computer-vision-and-multimodal-computing/research/people-detection-pose-estimation-and-tracking/multi-cue-onboard-pedestrian-detection/
Daimler http://www.gavrila.net/Research/Pedestrian_Detection/Daimler_Pedestrian_Benchmark_D/Daimler_Mono_Ped__Detection_Be/daimler_mono_ped__detection_be.html

![opencv_pedestrian_sample](https://cloud.githubusercontent.com/assets/17808301/16795054/3461c4ea-4916-11e6-8de5-534b81c13a69.jpg)
